# Generated by Django 2.1.15 on 2020-01-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(blank=True, choices=[('common', 'common'), ('designer', 'designer')], max_length=100, null=True, verbose_name='유저 타입'),
        ),
    ]
