# Generated by Django 2.1.15 on 2020-01-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200111_0159'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relations',
            unique_together={('from_user', 'to_user'), ('to_user', 'from_user')},
        ),
    ]
