# Generated by Django 2.1.15 on 2020-01-10 08:29

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.get_main_image_filename, verbose_name='메인 이미지'),
        ),
    ]
