# Generated by Django 2.1.15 on 2020-02-08 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': '게시글', 'verbose_name_plural': '게시글 목록'},
        ),
    ]
