# Generated by Django 2.1.15 on 2019-12-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='pyeong',
            field=models.CharField(default=1, max_length=20, verbose_name='평 수'),
            preserve_default=False,
        ),
    ]
