# Generated by Django 2.1.15 on 2020-01-16 09:27

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='Postimages',
            name='image_comment',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='사진 설명'),
        ),
        migrations.AlterField(
            model_name='Postimages',
            name='image',
            field=models.ImageField(upload_to=posts.models.get_image_filename, verbose_name='다중 이미지'),
        ),
    ]
