# Generated by Django 2.1.15 on 2020-01-16 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200116_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='colors',
            field=models.ManyToManyField(blank=True, null=True, to='posts.Colors'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_posts', related_query_name='like_post', through='posts.Postlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
